#Global Configurations

timezone: America/New_York
encoding: utf-8


# Site settings
title: Just me and my words
email: contactjaimer@gmail.com
description: > # I like to program, but programming doesn't define me. 
 It's a mere attribute, I also like poetry, I care about my Environment,
 I like to talk politics, I love to read Novels. I consider myself a lifetime
 student of life, and this is a place for me forward my knowledge to someone
 who might be interested;
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://Jaime-Reynoso.github.io/" # the base hostname & protocol for your site
github_username:  Jaime-Reynoso

# Build settings
markdown: rdiscount
permalink: pretty
paginate: 3
# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Sample Jekyll Blog

# Short description (goes below the title; it will also be used in the RSS feed)
description: This is a sample Jekyll Blog.

# Your name, as you want it to appear underneath each post and in the footer
author: Jaime Reynoso

# Your email if you want it to be linked on the contact page
author_email: contactjaimer@gmail.com
